package log

import (
	"github.com/src-d/envconfig"
)

// DefaultFactory used by the `log.New()` function. Pre-configured with the
// environment variables.
//
// The environment variables are autogenerated from the `LoggerFactory` fields,
// with a prefix `log`, it means that three different variables are available
// `LOG_LEVEL`, `LOG_FORMAT`, `LOG_FIELDS`, for more information about the
// values please read the `LoggerFactory` documentation.
var DefaultFactory *LoggerFactory

// New returns a new logger using `DefaultFactory`.
func New() (Logger, error) {
	if DefaultFactory == nil {
		DefaultFactory = &LoggerFactory{}
		if err := envconfig.Process("log", DefaultFactory); err != nil {
			return nil, err
		}
	}

	return DefaultFactory.New()
}
